/**
 * POST /api/admin/send-reset
 *
 * Admin-only. Generates a new temporary password for a tenant,
 * stores the hash in Airtable, and emails the new credentials via Resend.
 */

import { NextResponse } from 'next/server'
import { getTenantConfig, tenantError } from '@/lib/tenant'
import bcrypt from 'bcryptjs'

const PLATFORM_TOKEN = process.env.PLATFORM_AIRTABLE_TOKEN   || ''
const PLATFORM_BASE  = process.env.PLATFORM_AIRTABLE_BASE_ID || ''
const RESEND_KEY     = process.env.RESEND_API_KEY             || ''
const BASE_URL_SITE  = (process.env.NEXT_PUBLIC_BASE_URL || 'https://cb-dashboard-xi.vercel.app').replace(/\/$/, '')
const FROM           = 'Scout <noreply@clientbloom.ai>'

function generateTempPassword(): string {
  const chars = 'ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789'
  let pw = ''
  for (let i = 0; i < 12; i++) {
    pw += chars.charAt(Math.floor(Math.random() * chars.length))
  }
  return pw
}

export async function POST(req: Request) {
  const caller = await getTenantConfig()
  if (!caller) return tenantError()
  if (!caller.isAdmin) {
    return NextResponse.json({ error: 'Admin access required.' }, { status: 403 })
  }
  if (!RESEND_KEY) {
    return NextResponse.json({ error: 'RESEND_API_KEY not configured.' }, { status: 500 })
  }

  try {
    const { id, email, companyName } = await req.json()
    if (!id || !email) {
      return NextResponse.json({ error: 'id and email are required.' }, { status: 400 })
    }

    // Generate new temp password and hash it
    const tempPassword = generateTempPassword()
    const passwordHash = await bcrypt.hash(tempPassword, 12)

    // Store new hash in Airtable
    const patchResp = await fetch(
      `https://api.airtable.com/v0/${PLATFORM_BASE}/Tenants/${id}`,
      {
        method: 'PATCH',
        headers: {
          Authorization: `Bearer ${PLATFORM_TOKEN}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ fields: { 'Password Hash': passwordHash } }),
      }
    )
    if (!patchResp.ok) {
      return NextResponse.json({ error: 'Failed to update password in Airtable.' }, { status: 500 })
    }

    // Send email via Resend
    const html = `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;color:#1a1a1a">
        <div style="background:#4F6BFF;padding:20px 28px;border-radius:12px 12px 0 0">
          <p style="color:#fff;font-size:16px;font-weight:700;margin:0">Scout — Login Reset</p>
        </div>
        <div style="background:#f9f9f9;padding:28px 32px;border-radius:0 0 12px 12px;border:1px solid #e5e5e5;border-top:none">
          <h2 style="margin:0 0 8px;font-size:18px">Your login credentials have been reset</h2>
          <p style="color:#555;margin:0 0 24px;font-size:14px;line-height:1.6">
            Here are your updated login details for Scout${companyName ? ` (${companyName})` : ''}.
            Please sign in and change your password in Settings.
          </p>
          <table style="width:100%;border-collapse:collapse;font-size:14px;margin-bottom:24px">
            <tr style="border-bottom:1px solid #eee">
              <td style="padding:10px 0;color:#888;width:110px">Login URL</td>
              <td style="padding:10px 0">
                <a href="${BASE_URL_SITE}/sign-in" style="color:#4F6BFF;text-decoration:none">${BASE_URL_SITE}/sign-in</a>
              </td>
            </tr>
            <tr style="border-bottom:1px solid #eee">
              <td style="padding:10px 0;color:#888">Email</td>
              <td style="padding:10px 0;font-weight:500">${email}</td>
            </tr>
            <tr>
              <td style="padding:10px 0;color:#888">Password</td>
              <td style="padding:10px 0;font-family:monospace;font-size:16px;font-weight:700;letter-spacing:0.05em">${tempPassword}</td>
            </tr>
          </table>
          <a href="${BASE_URL_SITE}/sign-in"
             style="display:inline-block;background:#4F6BFF;color:#fff;font-weight:600;padding:11px 24px;border-radius:8px;text-decoration:none;font-size:14px">
            Sign in to Scout →
          </a>
          <p style="font-size:12px;color:#aaa;margin:20px 0 0">
            This password was generated by your Scout administrator.
            If you didn't expect this email, please contact support.
          </p>
        </div>
      </div>
    `

    const emailResp = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { Authorization: `Bearer ${RESEND_KEY}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        from:    FROM,
        to:      [email],
        subject: 'Your Scout login has been reset',
        html,
      }),
    })

    if (!emailResp.ok) {
      const body = await emailResp.text()
      return NextResponse.json({ error: `Email failed: ${body.slice(0, 200)}` }, { status: 500 })
    }

    return NextResponse.json({ ok: true })
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 })
  }
}
